package com.fooholdings.fdp.grocery.location;

import java.time.Instant;
import java.util.UUID;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

/**
 * JDBC-based write path for store_location.
 *
 * Uses ON CONFLICT DO UPDATE (upsert) for idempotent re-ingestion:
 *   - If the location has never been seen: INSERT new row (first_seen_at = now)
 *   - If already present: UPDATE mutable fields and last_seen_at only
 *   - first_seen_at is never overwritten (excluded from the UPDATE clause)
 *
 * Returns the UUID of the upserted row regardless of whether it was an
 * insert or update, needed by the calling service to correlate with
 * product / price ingestion.
 */
@Repository
public class StoreLocationJdbcRepository {

    private final JdbcTemplate jdbc;

    public StoreLocationJdbcRepository(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    /**
     * Upserts a store location row and returns its UUID.
     * The UUID is generated by the caller so it is stable on retries.
     */
    public UUID upsert(UUID id,
                       short sourceSystemId,
                       String sourceLocationId,
                       String chainCode,
                       String name,
                       String phone,
                       String addressLine1,
                       String city,
                       String stateCode,
                       String postalCode,
                       String countryCode) {

        Instant now = Instant.now();

        jdbc.update("""
                INSERT INTO fdp_grocery.store_location
                  (id, source_system_id, source_location_id, chain_code, name, phone,
                   address_line1, city, state_code, postal_code, country_code,
                   first_seen_at, last_seen_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT (source_system_id, source_location_id) DO UPDATE SET
                  name          = EXCLUDED.name,
                  phone         = EXCLUDED.phone,
                  address_line1 = EXCLUDED.address_line1,
                  city          = EXCLUDED.city,
                  state_code    = EXCLUDED.state_code,
                  postal_code   = EXCLUDED.postal_code,
                  country_code  = EXCLUDED.country_code,
                  last_seen_at  = EXCLUDED.last_seen_at
                """,
                id, sourceSystemId, sourceLocationId, chainCode, name, phone,
                addressLine1, city, stateCode, postalCode, countryCode,
                now, now
        );

        // Original id is preserved.
        // Retrieve it for the actual UUID (the caller's id is only used on INSERT)
        return jdbc.queryForObject(
                "SELECT id FROM fdp_grocery.store_location WHERE source_system_id = ? AND source_location_id = ?",
                UUID.class,
                sourceSystemId, sourceLocationId
        );
    }
}
